### PR TITLE
Issue #27 changes

### PR DESCRIPTION
**Pull request by naveenkaushik2504**
1.1 Not sure what exactly is needed as "description". Implemented the class name for now.
3. May be can be implemented whenever #19 is done.

### CODE REVIEW

**Comment by shaypal5** [comment]
Hey @naveenkaushik2504 ,

I'll take a look at the code itself ASAP, but in the meanwhile please note that it fails the linting job on Travis:
https://travis-ci.org/github/pdpipe/pdpipe/builds/722429711

Here's the output:
```
./pdpipe/sklearn_stages.py:212:80: E501 line too long (87 > 79 characters)
./pdpipe/sklearn_stages.py:238:80: E501 line too long (87 > 79 characters)
./pdpipe/col_generation.py:271:80: E501 line too long (97 > 79 characters)
./pdpipe/col_generation.py:695:80: E501 line too long (89 > 79 characters)
./pdpipe/col_generation.py:888:80: E501 line too long (88 > 79 characters)
./pdpipe/col_generation.py:903:80: E501 line too long (99 > 79 characters)
```

**Comment by naveenkaushik2504** [comment]
Apologies for missing the `flake8` requirement. I'll look into it. I'll fix it along with the other review comments.

**Comment by shaypal5** [comment]
Great, now let's make sure code coverage stays at a 100%, please. :)

**Comment by naveenkaushik2504** [comment]
Coverage is back on 100% @shaypal5

**Comment by shaypal5** [comment]
Nice! Looks good! I'm merging this.

**Pull request merged**
